#+TITLE:  Readme
#+AUTHOR: Andreas Gerler
#+EMAIL:  baron@bundesbrandschatzamt.de
#+DATE:   2016 Feb 11

* Overview

This is my collection of [[http://www.keyboardmaestro.com][Keyboard Maestro]] macros.

* Macros
** [[file:Edit_Anywhere.kmmacros][Edit_Anywhere]]

copied from https://github.com/tjluoma/edit-anywhere.git.
Added support for Emacs.

** [[file:screen-start-ssh-to-clipboard.kmmacros][screen-start-ssh-to-clipboard]]

A small macro to bring iTerm2 to front. Assumed running GNU
Screen. Open a new tab and ssh to what's in clipboard.
I have a small Emacs function calling this macro.
That way I can open a connection outside of Emacs. Something I still
occasionally do.

** Keypad Mac bindings
[2016-02-13 Sat 11:45]

Even though I love my [[http://www.pckeyboard.com/page/category/EnduraPro][UNICOMP Keyboards]] they lack the /fn/ keys for
Apple. These macros bring some of the functionality to /cmd/ plus
keypad number.

*** [[keypad-0-system-volume-mute-toggle.kmmacros][keypad-0-system-volume-mute-toggle]]
[2016-02-13 Sat 11:42]



*** [[keypad-1-system-volume-down.kmmacros][keypad-1-system-volume-down]]
[2016-02-13 Sat 11:44]

*** [[keypad-2-system-volume-up.kmmacros][keypad-2-system-volume-up]]
[2016-02-13 Sat 11:44]

*** [[keypad-5-itunes-pause.kmmacros][keypad-5-itunes-pause]]
[2016-02-13 Sat 11:44]
