#+TITLE:  Readme
#+AUTHOR: Andreas Gerler
#+EMAIL:  baron@bundesbrandschatzamt.de
#+DATE:   2016 Feb 11

* Overview

This is my collection of [[http://www.keyboardmaestro.com][Keyboard Maestro]] macros.

* Macros
** [[file:Edit_Anywhere.kmmacros][Edit_Anywhere]]

copied from https://github.com/tjluoma/edit-anywhere.git.
Added support for Emacs.

** [[file:screen-start-ssh-to-clipboard.kmmacros][screen-start-ssh-to-clipboard]]

A small macro to bring iTerm2 to front. Assumed running GNU
Screen. Open a new tab and ssh to what's in clipboard.
I have a small Emacs function calling this macro.
That way I can open a connection outside of Emacs. Something I still
occasionally do.

** [[file:screen-start-cd-to-clipboard.kmmacros][screen-start-cd-to-clipboard]]
[2018-07-26 Thu 11:10]

Another macro to bring iTerm2 to front. I assume it is running GNU
screen.
It opens a new tab and changes directory to what is in the clipboard.
My Emacs has a some functions to call this macro.

** [[file:iterm-insert-clipboard.kmmacros][iterm-insert-clipboard]]
[2018-10-10 Wed 14:33]

Bring iTerm2 to front and insert the current clipboard.
I use this to execute sql commands from Emacs.

** Keypad Mac bindings
[2016-02-13 Sat 11:45]

Even though I love my [[http://www.pckeyboard.com/page/category/EnduraPro][UNICOMP Keyboards]] they lack the /fn/ keys for
Apple. These macros bring some of the functionality to /cmd/ plus
keypad number.

*** [[keypad-0-system-volume-mute-toggle.kmmacros][keypad-0-system-volume-mute-toggle]]
[2016-02-13 Sat 11:42]



*** [[keypad-1-system-volume-down.kmmacros][keypad-1-system-volume-down]]
[2016-02-13 Sat 11:44]

*** [[keypad-2-system-volume-up.kmmacros][keypad-2-system-volume-up]]
[2016-02-13 Sat 11:44]

*** [[keypad-5-itunes-pause.kmmacros][keypad-5-itunes-pause]]
[2016-02-13 Sat 11:44]
*** [[keypad-6-itunes-skip.kmmacros][keypad-6-itunes-skip]]
[2018-07-26 Thu 11:07]

** [[lock-screen.kmmacros][lock-screen]]
[2016-02-22 Mon 15:09]

I don't have power button on my [[http://www.pckeyboard.com/page/category/EnduraPro][UNICOMP Keyboards]] but my muscle memory
is trained for ctrl ESC anyway since my Linux Desktop days.

** [[switch-to-emacs.kmmacros][switch-to-emacs]]
[2016-02-22 Mon 17:21]
Use Insert Key to switch instantly to Emacs.

** [[switch-to-iterm.kmmacros][switch-to-iterm]]
[2016-02-25 Thu 10:50]
Use CMD + Insert Key to switch instantly to iterm.
** [[iterm-launches.kmmacros][iterm-launches]]
[2016-02-26 Fri 16:20]
After iTerm launches check network and do the every morning task.
** [[login-items.kmmacros][login-items]]
[2016-10-21 Fri 16:56]
Start some processes after Keyboard Maestro. Otherwise macros like
iterm-launches are not triggered.
** [[move-window-to-other-screen.kmmacros][move-window-to-other-screen]]
[2016-10-21 Fri 16:57]
Send the active window to the second or third screen.
** [[toggle-pause-youtube-switch-to-emacs.kmmacros][toggle-pause-youtube-switch-to-emacs]]
[2016-10-21 Fri 16:58]
This one is nice if you want to take notes from a presentation on
youtube.
** [[toggle-maximize-window.kmmacros][toggle-maximize-window]]
[2016-10-21 Fri 17:00]
Resize the window via keyboard.
